### ISSUE TITLE
Flag could not be matched: 's'

### ISSUE THREAD

**Issue by DevAlone** [andrejlevkovitch/vim-lua-format#1]
> Flag could not be matched: 's'
  lua-format [Lua scripts...] {OPTIONS}
    Reformats your Lua source code.                                                                                                                                                     
  OPTIONS:
      -h, --help                        Display this help menu
      -v, --verbose                     Turn on verbose mode
      -i                                Reformats in-place
      --dump-config                     Dumps the default style used to stdout
      -c[file], --config=[file]         Style config file
      Lua scripts...                    Lua scripts to format
      "--" can be used to terminate flag options and force all following
      arguments to be treated as positional options
No output from lua-format (crashed?).
"main.lua" 12L, 158C written

Seems that the fix is to change `command = [binary, '-si']` to `command = [binary, '-i']` here https://github.com/andrejlevkovitch/vim-lua-format/blob/master/lua-format.py#L76

**Comment by dnebauer** [comment]
Encountered same bug and fixed it the same way.

**Comment by andrejlevkovitch** [comment]
@DevAlone thank about report. I used different version of `lua-format`, so in my case the flag was different. Now I change it to using latest flags of `lua-format`
