### ISSUE TITLE
Cannot find commands in neovim

### ISSUE THREAD

**Issue by adgai19** [andrejlevkovitch/vim-lua-format#3]
Hi, I tried installing vim-lua-format via vim-plug, but after installing I cannot find LuaFormat() in my command window. 
I can confirm that I have vim-lua-format installed and running inside viim-lua-format but command icannot be accessed inside neovim.

I am running neovim with following settings
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-HFtnIO/neovim-0.5.0+ubuntu2+git202103292336-aa6adacd7-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-HFtnIO/neovim-0.5.0+ubuntu2+git202103292336-aa6adacd7-d569569c9/build/config -I/build/neovim-HFtnIO/neovim-0.5.0+ubuntu2+git202103292336-aa6adacd7-d569569c9/src -I/build/neovim-HFtnIO/neovim-0.5.0+ubuntu2+git202103292336-aa6adacd7-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-HFtnIO/neovim-0.5.0+ubuntu2+git202103292336-aa6adacd7-d569569c9/build/src/nvim/auto -I/build/neovim-HFtnIO/neovim-0.5.0+ubuntu2+git202103292336-aa6adacd7-d569569c9/build/include
Compiled by buildd@lgw01-amd64-030

with vim-plug.

![Screenshot from 2021-03-31 19-58-16](https://user-images.githubusercontent.com/29275245/113161432-0268c800-925c-11eb-891d-3ac3ea65c880.png)

**Comment by andrejlevkovitch** [comment]
Do you install [LuaFormatter](https://github.com/Koihik/LuaFormatter)?

**Comment by adgai19** [comment]
Yes. And I am able to format the code in the terminal. I just cannot find LuaFormat() in command mode.

**Comment by andrejlevkovitch** [comment]
Hm, interesting. I never used neovim or vim-plug, but I don't see any reason for problems with they. Do you confident, that thd plugin succesfully loaded? Maybe you get error?

**Comment by adgai19** [comment]
> Hi, I tried installing vim-lua-format via vim-plug, but after installing I cannot find LuaFormat() in my command window.
> I can confirm that I have vim-lua-format installed and running inside viim-lua-format but command icannot be accessed inside neovim.
> 
> I am running neovim with following settings
> NVIM v0.5.0-dev
> Build type: RelWithDebInfo
> LuaJIT 2.1.0-beta3
> Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-HFtnIO/neovim-0.5.0+ubuntu2+git202103292336-aa6adacd7-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-HFtnIO/neovim-0.5.0+ubuntu2+git202103292336-aa6adacd7-d569569c9/build/config -I/build/neovim-HFtnIO/neovim-0.5.0+ubuntu2+git202103292336-aa6adacd7-d569569c9/src -I/build/neovim-HFtnIO/neovim-0.5.0+ubuntu2+git202103292336-aa6adacd7-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-HFtnIO/neovim-0.5.0+ubuntu2+git202103292336-aa6adacd7-d569569c9/build/src/nvim/auto -I/build/neovim-HFtnIO/neovim-0.5.0+ubuntu2+git202103292336-aa6adacd7-d569569c9/build/include
> Compiled by buildd@lgw01-amd64-030
> 
> with vim-plug.
> 
> ![Screenshot from 2021-03-31 19-58-16](https://user-images.githubusercontent.com/29275245/113161432-0268c800-925c-11eb-891d-3ac3ea65c880.png)

Yes. I tried checking the status of plugin. The screenshot attached to this message shows that it is active and loaded.

**Comment by andrejlevkovitch** [comment]
So, I don't know what kind of problem here can be... Can you try to use vundle instead of vim-plug?

**Comment by adgai19** [comment]
I tried vundle instead of vim-plug. I still cannot access it.

**Comment by andrejlevkovitch** [comment]
Sorry, but I completely don't know how I can help you...

**Comment by andrejlevkovitch** [comment]
Or know... What you try to do? You try just call `:LuaFormat()` in command mode?

**Comment by adgai19** [comment]
I cannot access `:LuaFormat()` in command mode. I get it as not an editor command.

**Comment by andrejlevkovitch** [comment]
So, it is a wrong call. `LuaFormat()` is a function, so if you want call it you need do this explicitly: `:call LuaFormat()`

**Comment by adgai19** [comment]
That worked. Thanks a lot. I am still a newbie at vim. So didn't think of that

**Comment by andrejlevkovitch** [comment]
You're welcome)

**Comment by andrejlevkovitch** [comment]
I will add it to the description
